### ISSUE TITLE
selectScenario is not selecting the requested scenario

### ISSUE THREAD

**Issue by Local9** [mdasberg/ng-apimock#40]
I'm calling `ngApimock.selectScenario('welcome', 'welcome-new-title');` correctly in my step but it is only acting as a pass through unless default is defined true, to test this I added another scenario. Am I getting something wrong?

Mock file: welcome.json
```
{
  "expression": "api\/v1\/welcome",
  "method": "GET",
  "name": "welcome",
  "isArray": "false",
  "responses": {
    "welcome-title": {
      "default": true,
      "status": 200,
      "headers": {},
      "data": { "message": "Welcome to app!!" }
    },
    "welcome-new-title": {
      "default": false,
      "status": 200,
      "headers": {},
      "data": { "message": "Welcome to the new app!!" }
    }
  }
}
```
service http request:
```
getWelcome() {
    return this.http.get('api/v1/welcome').map(response => response.json())
    .catch((error: Response | any) => {
      return Observable.throw(error.json());
    }).toPromise();
  }
```
Edit: I'm being returned "Cannot GET /api/v1/welcome" on the mocking page

Edit: Updated expression to regex match (regex101.com), still same issue.

**Comment by mdasberg** [comment]
I've tried to reproduce your situation, but when I use your mock and I call the url I get the correct answer.

When I call the url without changing the scenario I get 

```
curl http://localhost:9900/api/v1/welcome
```
results in 
```
{"message": "Welcome to app!!"}
```

When I call the url after selecting the scenario "welcome-new-title" I get this
 ```
curl http://localhost:9900/api/v1/welcome
```
results in 
```
{"message": "Welcome to the new app!!"}
```

can you show me your setup?

**Comment by Local9** [comment]
My setup is here: https://github.com/Local9/AngularBDD-serenityJS

**Comment by mdasberg** [comment]
I just checked out your repo and checked the code.

in your [mock file](https://github.com/Local9/AngularBDD-serenityJS/blob/master/mocks/welcome.json) you have both scenarios set to **false** which results in a **passThrough**.

when you call **ngApimock.selectScenario** in your [po file](https://github.com/Local9/AngularBDD-serenityJS/blob/master/e2e/app.po.ts) like this:
```
navigateTo() {
    return ngApimock.selectScenario('welcome', 'welcome-title').then(()=> {
      return browser.get('/');
    })
  }
```

your tests is succesful

**Comment by Local9** [comment]
Ok so selectScenario returns a promise which will then make it return the correct scenario?

**Comment by mdasberg** [comment]
yes every method on ngApimock returns a promise.

**Comment by Local9** [comment]
Sorry to re-open this, same issue still remains using selectScenario, am I reading this wrong?!

> selectScenario(name, scenarioName, options)
>
>Selects the given scenario (when calling this function without a scenario or with 'passThrough' as scenario name, the call will be passed through to the actual backend)

I am declaring which scenario I want it to use but it is not, I can see it making the calls to the API layer when running my tests but the scenario is not correctly selected.

Process;
- Run the API `npm run api`
- Run e2e tests with proxy `npm run e2e` this will serve the application and also use the configured proxy

BDD Testing with Cucumber;
- Run the API `npm run api`
- Serve the APP `npm start`
- Run BDD tests `npm run bdd`

Neither change from the default scenario. So am I reading your method wrong in that I should be allowed to change the scenario my tests run in my tests or is this not the case?

**Comment by Local9** [comment]
So, spent the day back on this after doing a bunch of updates to me repo... still doesn't work.

If I set the mock on the mocking page, works as expected. So select scenario method work as I expected. I can see the PUT, but the GET returns nothing, from my understanding this should set the scenario, just like the drop down on the mocking page

Console Output;

```
C:\Users\acook\workspace\ng2\AngularBDD-serenityJS>ng e2e
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building modules 3/3 modules 0 active[HPM] Proxy created: /api  ->  http://localhost:3000
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[HPM] Proxy created: /ngapimock  ->  http://localhost:3000
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]

Date: 2019-01-12T12:26:19.847Z
Hash: dadd9efa9550cf70dc4e
Time: 9008ms
chunk {main} main.js, main.js.map (main) 14.5 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 259 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.3 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.97 MB [initial] [rendered]
i ?wdm?: Compiled successfully.
[12:26:20] I/update - chromedriver: file exists C:\Users\acook\workspace\ng2\AngularBDD-serenityJS\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.45.zip
[12:26:20] I/update - chromedriver: unzipping chromedriver_2.45.zip
[12:26:20] I/update - chromedriver: chromedriver_2.45.exe up to date
C:\Users\acook\workspace\ng2\AngularBDD-serenityJS
[12:26:21] I/launcher - Running 1 instances of WebDriver
[12:26:21] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:50726/devtools/browser/1cc06d36-b1bb-41fa-a61c-6802ea3d0d81
.[HPM] PUT /ngapimock/mocks -> http://localhost:3000
[HPM] GET /api/v1/welcome -> http://localhost:3000
[HPM] GET /api/v1/welcome -> http://localhost:3000
.F.

Failures:

1) Scenario: I open the homepage and see a welcome message # e2e\features\welcome\welcome.feature:5
   V Before # e2e\steps\welcome\welcome_check.steps.ts:11
   V Given I am on the homepage # e2e\steps\welcome\welcome_check.steps.ts:15
   × Then I should see welcome message # e2e\steps\welcome\welcome_check.steps.ts:18
       AssertionError
           + expected - actual

           -app
           +Welcome to the app!!

           at C:\Users\acook\workspace\ng2\AngularBDD-serenityJS\e2e\steps\welcome\welcome_check.steps.ts:20:18
           at elementArrayFinder_.then (C:\Users\acook\workspace\ng2\AngularBDD-serenityJS\node_modules\protractor\built\element.js:804:32)
           at ManagedPromise.invokeCallback_ (C:\Users\acook\workspace\ng2\AngularBDD-serenityJS\node_modules\selenium-webdriver\lib\promise.js:1376:14)
           at TaskQueue.execute_ (C:\Users\acook\workspace\ng2\AngularBDD-serenityJS\node_modules\selenium-webdriver\lib\promise.js:3084:14)
           at TaskQueue.executeNext_ (C:\Users\acook\workspace\ng2\AngularBDD-serenityJS\node_modules\selenium-webdriver\lib\promise.js:3067:27)
           at asyncRun (C:\Users\acook\workspace\ng2\AngularBDD-serenityJS\node_modules\selenium-webdriver\lib\promise.js:2927:27)
           at C:\Users\acook\workspace\ng2\AngularBDD-serenityJS\node_modules\selenium-webdriver\lib\promise.js:668:7
           at <anonymous>
           at process._tickCallback (internal/process/next_tick.js:118:7)
   V After # node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:26

1 scenario (1 failed)
2 steps (1 failed, 1 passed)
0m00.987s
[12:26:24] I/launcher - 0 instance(s) of WebDriver still running
[12:26:24] I/launcher - chrome #01 failed 1 test(s)
[12:26:24] I/launcher - overall: 1 failed spec(s)
[12:26:24] E/launcher - Process exited with error code 1
An unexpected error occurred: undefined

C:\Users\acook\workspace\ng2\AngularBDD-serenityJS>
```

welcome.po.ts;
https://github.com/Local9/AngularBDD-serenityJS/blob/master/e2e/steps/welcome/welcome.po.ts

The response recorded;
```
{
  "mocks": [
    {
      "expression": "api/v1/welcome",
      "method": "GET",
      "name": "welcome",
      "isArray": "false",
      "responses": {
        "welcome-title": {
          "status": 200,
          "data": {
            "message": "Welcome to the app!!"
          }
        },
        "welcome-new-title": {
          "status": 200,
          "data": {
            "message": "Welcome to the new app!!"
          }
        }
      },
      "identifier": "welcome"
    }
  ],
  "selections": {},
  "delays": {},
  "echos": {},
  "recordings": {
    "welcome": [
      {
        "data": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /api/v1/welcome</pre>\n</body>\n</html>\n",
        "payload": "",
        "datetime": 1547295984677,
        "method": "GET",
        "url": "/api/v1/welcome",
        "statusCode": 404
      },
      {
        "data": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /api/v1/welcome</pre>\n</body>\n</html>\n",
        "payload": "",
        "datetime": 1547296595151,
        "method": "GET",
        "url": "/api/v1/welcome",
        "statusCode": 404
      }
    ]
  },
  "record": true
}
```

**Comment by mdasberg** [comment]
@Local9 I will checkout the project and try to figure out what is going wrong.

**Comment by Local9** [comment]
I swear its something simple. If you have any questions I'll answer them asap.
